#!/usr/bin/env bash
# Generates one .mobileconfig for iPad/iPad Pro demo setup that does in a
# single install what would otherwise take three separate manual steps:
#   1. Trusts the Caddy LAN root CA (from `make caddy-trust`)
#   2. Adds a "Bede" Home Screen icon pointing straight at this LAN server
#
# Usage: bash ipad-profile.sh [cert-file] [lan-ip]
#   (both arguments are optional — cert defaults to sage-root-ca.crt,
#    LAN IP is auto-detected the same way setup.sh does)
#
# After generating bede-ipad.mobileconfig:
#   AirDrop it to the iPad (or host it and open the link in Safari), then:
#     Settings -> Profile Downloaded -> Install
#     Settings -> General -> About -> Certificate Trust Settings
#       -> enable full trust for "Bede LAN Root CA"
#   That second step can't be skipped — iOS requires explicit user opt-in
#   for every installed root CA no matter how it was delivered. Everything
#   else (cert install + Home Screen icon) happens in the one profile install.
set -euo pipefail

CERT_FILE="${1:-sage-root-ca.crt}"
LAN_IP="${2:-$(hostname -I 2>/dev/null | awk '{print $1}')}"
ICON_FILE="homeschool-tutor/public/agnus-dei.png"
OUT="bede-ipad.mobileconfig"

[[ -f "$CERT_FILE" ]] || { echo "Missing $CERT_FILE — run 'make caddy-trust' first (requires the stack to be running)."; exit 1; }
[[ -n "$LAN_IP" ]] || { echo "Could not detect a LAN IP. Pass it explicitly: bash ipad-profile.sh $CERT_FILE 192.168.1.50"; exit 1; }

new_uuid() {
  if command -v uuidgen >/dev/null 2>&1; then uuidgen
  elif command -v python3 >/dev/null 2>&1; then python3 -c "import uuid; print(uuid.uuid4())"
  else cat /proc/sys/kernel/random/uuid
  fi
}

CERT_B64=$(base64 "$CERT_FILE" | tr -d '\n')
UUID_CERT=$(new_uuid)
UUID_CLIP=$(new_uuid)
UUID_PROFILE=$(new_uuid)

ICON_TAG=""
if [[ -f "$ICON_FILE" ]]; then
  ICON_B64=$(base64 "$ICON_FILE" | tr -d '\n')
  ICON_TAG="<key>Icon</key>
            <data>${ICON_B64}</data>"
fi

cat > "$OUT" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>PayloadContent</key>
    <array>
        <dict>
            <key>PayloadCertificateFileName</key>
            <string>sage-root-ca.crt</string>
            <key>PayloadContent</key>
            <data>${CERT_B64}</data>
            <key>PayloadDescription</key>
            <string>Trusts the Bede LAN server's local TLS certificate authority (generated by Caddy).</string>
            <key>PayloadDisplayName</key>
            <string>Bede LAN Root CA</string>
            <key>PayloadIdentifier</key>
            <string>ai.agnusdei.bede.rootca</string>
            <key>PayloadType</key>
            <string>com.apple.security.root</string>
            <key>PayloadUUID</key>
            <string>${UUID_CERT}</string>
            <key>PayloadVersion</key>
            <integer>1</integer>
        </dict>
        <dict>
            <key>FullScreen</key>
            <true/>
            ${ICON_TAG}
            <key>IsRemovable</key>
            <true/>
            <key>Label</key>
            <string>Bede</string>
            <key>Precomposed</key>
            <true/>
            <key>PayloadDescription</key>
            <string>Adds a Home Screen icon that opens Bede directly.</string>
            <key>PayloadDisplayName</key>
            <string>Bede Home Screen Icon</string>
            <key>PayloadIdentifier</key>
            <string>ai.agnusdei.bede.webclip</string>
            <key>PayloadType</key>
            <string>com.apple.webClip.managed</string>
            <key>PayloadUUID</key>
            <string>${UUID_CLIP}</string>
            <key>PayloadVersion</key>
            <integer>1</integer>
            <key>URL</key>
            <string>https://${LAN_IP}</string>
        </dict>
    </array>
    <key>PayloadDescription</key>
    <string>One-tap setup for the Bede demo iPad: trusts the LAN server's certificate and adds a Home Screen icon.</string>
    <key>PayloadDisplayName</key>
    <string>Bede iPad Setup</string>
    <key>PayloadIdentifier</key>
    <string>ai.agnusdei.bede.ipadsetup</string>
    <key>PayloadOrganization</key>
    <string>Bede</string>
    <key>PayloadRemovalDisallowed</key>
    <false/>
    <key>PayloadType</key>
    <string>Configuration</string>
    <key>PayloadUUID</key>
    <string>${UUID_PROFILE}</string>
    <key>PayloadVersion</key>
    <integer>1</integer>
</dict>
</plist>
EOF

echo "Wrote ${OUT}"
echo ""
echo "Install on the iPad:"
echo "  1. AirDrop ${OUT} to the iPad (or serve it: python3 -m http.server 8080, then open"
echo "     http://<this-host-ip>:8080/${OUT} in Safari on the iPad)"
echo "  2. Settings -> Profile Downloaded -> Install (enter passcode)"
echo "  3. Settings -> General -> About -> Certificate Trust Settings"
echo "     -> enable full trust for 'Bede LAN Root CA'  (required by iOS — can't be skipped)"
echo ""
echo "A 'Bede' icon appears on the Home Screen pointing at https://${LAN_IP} — no separate"
echo "'Add to Home Screen' step needed."
