"""
Bede license verification — see docs/PRODUCTION_SETUP.md#licensing.

A license is a compact, offline-verifiable certificate:

    base64url(payload_json) + "." + base64url(ed25519_signature)

No phone-home, no license server, no telemetry — verification happens
entirely against the embedded PUBLIC_KEY_PEM below, at startup
(core/config.py). That's a deliberate fit with Bede's self-hosted/LAN-only
design: a deployment never needs outbound network access to prove it's
licensed, and a family's own server never reports back to us.

Issuing a license (operator-only — requires the private key, which is
never committed to this repo; see scripts/generate_license_keypair.py):

    python scripts/issue_license.py --tier core --licensee "The Smith Family" \\
        --seats 10 --private-key /path/to/private.pem

Threat model: this is a trust-and-verify gate for honest self-hosters, not
DRM. Anyone with the source (which every self-hosted deployer has) could
patch this check out entirely — no signature scheme prevents that. What it
does prevent is a casual copy of a license string being silently accepted
by a *different* tier/seat count than what was actually issued.
"""
import base64
import json
from dataclasses import dataclass
from datetime import date
from functools import lru_cache
from typing import Optional

from Crypto.PublicKey import ECC
from Crypto.Signature import eddsa

# Public half of the operator's Ed25519 signing key. Safe to embed — it can
# only verify licenses, never mint them. Generated by
# scripts/generate_license_keypair.py; the matching private key lives
# offline, outside this repo.
PUBLIC_KEY_PEM = """-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEABpTf5ffiiNf0OItRYP3R2pLb7ij/KtNOS73WPBq57N4=
-----END PUBLIC KEY-----"""

_VALID_TIERS = {"trial", "core", "coop"}


class InvalidLicenseError(Exception):
    """Malformed, tampered, or structurally invalid license string.

    Expiry is deliberately NOT treated as invalid here — see
    LicenseInfo.is_expired. A caller may still want to display an expired
    license's details (tier, licensee, "expired on ...") rather than just
    reject it outright, so parsing succeeds and the caller decides what an
    expired result means for them.
    """


@dataclass(frozen=True)
class LicenseInfo:
    license_id: str
    licensee: str
    tier: str
    seats: int
    issued: date
    expires: Optional[date]

    @property
    def is_expired(self) -> bool:
        return self.expires is not None and self.expires < date.today()

    @property
    def days_remaining(self) -> Optional[int]:
        if self.expires is None:
            return None
        return (self.expires - date.today()).days


def _b64url_decode(s: str) -> bytes:
    padding = "=" * (-len(s) % 4)
    return base64.urlsafe_b64decode(s + padding)


def verify_license(license_str: str) -> LicenseInfo:
    """Verify a license string's signature and structure.

    Raises InvalidLicenseError for anything cryptographically or
    structurally wrong (bad format, tampered payload, unknown tier,
    missing fields). Does NOT raise for an already-expired license —
    check the result's .is_expired for that.
    """
    parts = license_str.strip().split(".")
    if len(parts) != 2:
        raise InvalidLicenseError("malformed license string (expected payload.signature)")

    try:
        payload_bytes = _b64url_decode(parts[0])
        signature_bytes = _b64url_decode(parts[1])
    except Exception as exc:
        raise InvalidLicenseError("malformed license encoding") from exc

    try:
        public_key = ECC.import_key(PUBLIC_KEY_PEM)
        eddsa.new(public_key, "rfc8032").verify(payload_bytes, signature_bytes)
    except ValueError as exc:
        raise InvalidLicenseError("signature verification failed — not a genuine Bede license") from exc

    try:
        payload = json.loads(payload_bytes)
        tier = payload["tier"]
        if tier not in _VALID_TIERS:
            raise InvalidLicenseError(f"unknown license tier {tier!r}")
        seats = int(payload["seats"])
        issued = date.fromisoformat(payload["issued"])
        expires = date.fromisoformat(payload["expires"]) if payload.get("expires") else None
        license_id = str(payload["id"])
        licensee = str(payload["licensee"])
    except InvalidLicenseError:
        raise
    except Exception as exc:
        raise InvalidLicenseError("malformed license payload") from exc

    return LicenseInfo(
        license_id=license_id,
        licensee=licensee,
        tier=tier,
        seats=seats,
        issued=issued,
        expires=expires,
    )


@lru_cache(maxsize=4)
def _cached_verify(license_str: str) -> LicenseInfo:
    return verify_license(license_str)


def get_license(license_key: str) -> Optional[LicenseInfo]:
    """Convenience wrapper for call sites outside config.py's startup
    validation (routers/pod.py's seat cap, routers/admin.py's status).
    Returns None for an unset key — dev/self-managed mode, no enforcement,
    same "empty = disabled" pattern as DEMO_PIN/SANDBOX_PIN. A non-empty
    key that fails to verify raises InvalidLicenseError; in production
    that can't happen post-startup (core/config.py already rejected a bad
    key before the app came up), so callers don't need to re-guard it.
    """
    if not license_key:
        return None
    return _cached_verify(license_key)
