/**
 * Generated alongside ed25519-cross-language.json by
 * license-server/scripts/generate-cross-language-vector.mjs — DO NOT EDIT
 * either by hand; regenerate instead. This module exists because the
 * workerd vitest pool cannot import JSON, while the Python cross-language
 * test reads the JSON twin.
 */
export interface CrossLanguageVector {
  comment: string;
  public_key_pem: string;
  private_key_pem: string;
  payload: Record<string, string | number>;
  payload_json: string;
  payload_json_b64url: string;
  signature_b64url: string;
  license_key: string;
}

export const VECTOR: CrossLanguageVector = {
  "comment": "TEST-ONLY throwaway keypair — generated by license-server/scripts/generate-cross-language-vector.mjs. NEVER paste a real signing key here: this file is public, and the real private key's public half is core/licensing.py's PUBLIC_KEY_PEM (see homeschool-api/tests/test_license_server_cross_language.py, which asserts the two differ). See the generator's docstring for what this vector proves (spec D1).",
  "public_key_pem": "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEA0YBaAkt8tNHpa94SbJR4BOGuTv5tVJ3MMZs8+dWv75Q=\n-----END PUBLIC KEY-----",
  "private_key_pem": "-----BEGIN PRIVATE KEY-----\nMC4CAQAwBQYDK2VwBCIEIE78AlikZUwDl8Jg36hW8uWW6qVXARg/+KvhS0gKxd6q\n-----END PRIVATE KEY-----",
  "payload": {
    "id": "6f6a1c66-0e11-4c5e-9a3f-8f2f5a4c9b01",
    "licensee": "storefront-test-family@example.com",
    "tier": "core",
    "seats": 6,
    "issued": "2026-10-10",
    "expires": "2031-10-09"
  },
  "payload_json": "{\"expires\":\"2031-10-09\",\"id\":\"6f6a1c66-0e11-4c5e-9a3f-8f2f5a4c9b01\",\"issued\":\"2026-10-10\",\"licensee\":\"storefront-test-family@example.com\",\"seats\":6,\"tier\":\"core\"}",
  "payload_json_b64url": "eyJleHBpcmVzIjoiMjAzMS0xMC0wOSIsImlkIjoiNmY2YTFjNjYtMGUxMS00YzVlLTlhM2YtOGYyZjVhNGM5YjAxIiwiaXNzdWVkIjoiMjAyNi0xMC0xMCIsImxpY2Vuc2VlIjoic3RvcmVmcm9udC10ZXN0LWZhbWlseUBleGFtcGxlLmNvbSIsInNlYXRzIjo2LCJ0aWVyIjoiY29yZSJ9",
  "signature_b64url": "oSXaEHh5sfONyIl9xCrnFWHUlmxoZS-ZroBf7AvpRl1RJkTI-6bH44rVe2m0mTLynRQUxP8zXIkMbOnlQYQGCQ",
  "license_key": "eyJleHBpcmVzIjoiMjAzMS0xMC0wOSIsImlkIjoiNmY2YTFjNjYtMGUxMS00YzVlLTlhM2YtOGYyZjVhNGM5YjAxIiwiaXNzdWVkIjoiMjAyNi0xMC0xMCIsImxpY2Vuc2VlIjoic3RvcmVmcm9udC10ZXN0LWZhbWlseUBleGFtcGxlLmNvbSIsInNlYXRzIjo2LCJ0aWVyIjoiY29yZSJ9.oSXaEHh5sfONyIl9xCrnFWHUlmxoZS-ZroBf7AvpRl1RJkTI-6bH44rVe2m0mTLynRQUxP8zXIkMbOnlQYQGCQ"
};
